# Generated by Django 4.2.26 on 2025-11-28 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_movil_escolar_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('es_estudiantes', models.BooleanField(default=False)),
                ('es_profesores', models.BooleanField(default=False)),
                ('es_publico', models.BooleanField(default=False)),
                ('programa', models.CharField(blank=True, choices=[('Ingeniería en Ciencias de la Computación', 'Ingeniería en Ciencias de la Computación'), ('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ciencias de la Computación'), ('Ingeniería en Tecnologías de la Información', 'Ingeniería en Tecnologías de la Información')], max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
